INSERT INTO players (name, order_index) VALUES
  ('Andre', 1),
  ('Brian', 2),
  ('Elia', 3),
  ('Felix', 4),
  ('Flo', 5),
  ('Georg', 6),
  ('Jakob', 7),
  ('Jan', 8),
  ('Janick', 9),
  ('Kris', 10),
  ('Lasse', 11),
  ('Lennard Grüner', 12),
  ('Lennard Steib', 13),
  ('Marius', 14),
  ('Nico', 15),
  ('Nicolas', 16),
  ('Niklas', 17),
  ('Noah Nicklin', 18),
  ('Noah Tefera', 19),
  ('Pascal', 20),
  ('Paul S', 21),
  ('Paul T', 22),
  ('Pölzi', 23),
  ('Phillip O', 24),
  ('Sammy', 25),
  ('Sebi May', 26),
  ('Sebastian Schmitt', 27),
  ('Thomas', 28),
  ('Tim P', 29),
  ('Timmy', 30),
  ('Tizi', 31),
  ('Tobi', 32);
